"""Synthetic arithmetic only: no NHIS source records or population estimates."""

from copy import deepcopy
from fractions import Fraction
from itertools import combinations
import json

import numpy as np
import pandas as pd
import pytest

from demeter.data.nhis_diagnosis_labels import CATEGORIES
from demeter.data.nhis_survey_witness import assess


def fixture():
    # Every category, including unknowns and contradiction, has explicit support.
    frame = pd.DataFrame(
        {
            "DIBEV_A": ["2", "1", "1", "1", "1", "9", "2", "1"],
            "DIBTYPE_A": ["", "1", "2", "3", "7", "", "2", "2"],
            "WTFA_A": [1, 2, 3, 4, 5, 6, 7, 8],
            "PSTRAT": [1, 1, 1, 1, 2, 2, 2, 2],
            "PPSU": [1, 1, 2, 3, 1, 2, 2, 3],
        },
        index=pd.Index(range(100, 108), name="private_synthetic_key"),
    )
    domains = pd.DataFrame(
        {"all": [True] * 8, "overlap": [True, False, True, False, True, True, False, True]},
        index=frame.index,
    )
    return frame, domains


def oracle(frame, domains):
    """Exact rational PSU-pair differences, independent of kernel centering.

    Toy category identities are specified directly, not generated by the adapter.
    """
    labels = list(CATEGORIES) + ["reported_type2"]
    w = [Fraction(value) for value in frame.WTFA_A]
    design = list(zip(frame.PSTRAT, frame.PPSU, strict=True))
    support = sorted(set(design))
    estimates, scores = [], []
    for name in domains:
        mask = list(domains[name])
        denominator = sum(weight for weight, selected in zip(w, mask, strict=True) if selected)
        for category in CATEGORIES:
            y = [int(label == category) for label in labels]
            p = (
                sum(
                    weight * value
                    for weight, value, selected in zip(w, y, mask, strict=True)
                    if selected
                )
                / denominator
            )
            estimates.append(float(p))
            scores.append(
                {
                    key: sum(
                        weight * (value - p) / denominator
                        for weight, value, selected, row_key in zip(w, y, mask, design, strict=True)
                        if selected and row_key == key
                    )
                    for key in support
                }
            )
    covariance = [[Fraction(0) for _ in scores] for _ in scores]
    for stratum in sorted({key[0] for key in support}):
        keys = [key for key in support if key[0] == stratum]
        for left, right in combinations(keys, 2):
            differences = [score[left] - score[right] for score in scores]
            for i, first in enumerate(differences):
                for j, second in enumerate(differences):
                    covariance[i][j] += first * second / (len(keys) - 1)
    return estimates, [[float(value) for value in row] for row in covariance]


def test_independent_fraction_oracle_and_complete_partition_dependence():
    frame, domains = fixture()
    result = assess(frame, domains)
    expected, covariance = oracle(frame, domains)
    assert result["joint"]["coordinates"] == [
        {"domain": domain, "membership": member} for domain in domains for member in CATEGORIES
    ]
    np.testing.assert_allclose(result["joint"]["ratios"], expected, rtol=2e-15, atol=2e-17)
    np.testing.assert_allclose(result["joint"]["covariance"], covariance, rtol=3e-15, atol=2e-17)
    matrix = np.array(result["joint"]["covariance"])
    for start in (0, 7):
        assert sum(result["joint"]["ratios"][start : start + 7]) == pytest.approx(1)
        np.testing.assert_allclose(matrix[:, start : start + 7].sum(axis=1), 0, atol=2e-17)
    assert np.any(matrix[:7, :7] < 0)  # Complete partition is not independent estimates.
    assert matrix[0, 7] != 0  # Overlapping domains retain cross-domain covariance.
    assert result["record_ledger"]["category_counts"] == dict.fromkeys(CATEGORIES, 1) | {
        "reported_type2": 2
    }
    assert result["record_ledger"]["total_records"] == 8
    assert result["record_ledger"]["ledger_conserved"]


def test_empty_domain_is_unavailable_and_outside_domain_psus_remain():
    frame, domains = fixture()
    domains["one"] = [True] + [False] * 7
    domains["empty"] = False
    result = assess(frame, domains)
    assert result["design"]["input_records"] == 8
    assert result["design"]["psus"] == 6
    assert result["domains"][-2]["represented_psus"] == 1
    assert result["domains"][-1]["status"] == "empty_domain"
    assert result["joint"]["ratios"][-7:] == [None] * 7
    assert all(value is None for row in result["joint"]["covariance"][-7:] for value in row)
    assert all(row[-7:] == [None] * 7 for row in result["joint"]["covariance"])


@pytest.mark.parametrize("scale", [1e-100, 10, 1e100])
def test_common_weight_scaling_and_record_order_preserve_arithmetic(scale):
    frame, domains = fixture()
    original = assess(frame, domains)
    frame["WTFA_A"] = frame.WTFA_A * scale
    order = [7, 2, 4, 0, 6, 1, 5, 3]
    result = assess(frame.iloc[order], domains.iloc[order])
    np.testing.assert_allclose(result["joint"]["ratios"], original["joint"]["ratios"], atol=2e-16)
    np.testing.assert_allclose(
        result["joint"]["covariance"], original["joint"]["covariance"], atol=2e-16
    )
    assert result["record_ledger"] == original["record_ledger"]


def test_private_validation_metadata_and_inputs_are_not_mutated():
    frame, domains = fixture()
    frame["WTSAFPRP"] = -999  # Irrelevant legacy alias must not replace native weights.
    before_frame, before_domains = deepcopy(frame), deepcopy(domains)
    result = assess(frame, domains)
    pd.testing.assert_frame_equal(frame, before_frame)
    pd.testing.assert_frame_equal(domains, before_domains)
    assert result["source_admitted"] is False
    assert all(
        result[name] is True
        for name in ("private_aggregate", "validation_only", "software_witness")
    )
    assert result["scientific_gates"] == dict.fromkeys(
        (
            "direct_initialization_allowed",
            "clinical_fit_allowed",
            "engine_activation_allowed",
            "sampling_distribution_assumed",
            "scientific_release_ready",
        ),
        False,
    )
    encoded = json.dumps(result)
    for forbidden in (
        "degrees_of_freedom",
        "confidence_interval",
        "reliability",
        "WTSAFPRP",
        "SDMVSTRA",
        "SDMVPSU",
        "NHANES",
        "private_synthetic_key",
    ):
        assert forbidden not in encoded
    assert result["joint"]["ratio_unit"] == "dimensionless"
    assert result["joint"]["covariance_unit"] == "dimensionless_squared"
    assert result["record_ledger"]["unit"] == "input_records"


@pytest.mark.parametrize("value", [0, -1, np.nan, np.inf, True, "2", 1j])
def test_unsupported_weight_refuses_without_trimming(value):
    frame, domains = fixture()
    frame["WTFA_A"] = pd.Series([value] * len(frame), index=frame.index)
    with pytest.raises(ValueError, match="software method"):
        assess(frame, domains)


@pytest.mark.parametrize("field", ["PSTRAT", "PPSU"])
@pytest.mark.parametrize("value", [np.nan, np.inf, True, "2", 1j])
def test_unsupported_design_values_refuse(field, value):
    frame, domains = fixture()
    frame[field] = pd.Series([value] * len(frame), index=frame.index)
    with pytest.raises(ValueError, match="software method"):
        assess(frame, domains)


def test_full_design_singleton_refused_even_when_all_domains_empty():
    frame, domains = fixture()
    frame.loc[frame.PSTRAT == 2, "PPSU"] = 1
    domains[:] = False
    with pytest.raises(ValueError, match="software method"):
        assess(frame, domains)


@pytest.mark.parametrize(
    "diagnosis,kind", [(1, "2"), (True, "2"), ("1", 2), ("1", None), ("secret", "2"), ("1", "\t")]
)
def test_invalid_native_categories_are_sanitized(diagnosis, kind):
    frame, domains = fixture()
    frame["DIBEV_A"] = pd.Series([diagnosis] * len(frame), index=frame.index)
    frame["DIBTYPE_A"] = pd.Series([kind] * len(frame), index=frame.index)
    with pytest.raises(ValueError) as failure:
        assess(frame, domains)
    assert "secret" not in str(failure.value)
    assert failure.value.__cause__ is None


@pytest.mark.parametrize(
    "case",
    [
        "missing_field",
        "duplicate_field",
        "duplicate_index",
        "missing_index",
        "empty",
        "domain_order",
        "nonboolean",
        "missing_domain",
        "duplicate_domain",
        "no_domain",
        "not_frame",
        "not_domains",
    ],
)
def test_invalid_shapes_refuse(case):
    frame, domains = fixture()
    if case == "missing_field":
        frame = frame.drop(columns="DIBEV_A")
    elif case == "duplicate_field":
        frame = pd.concat([frame, frame[["DIBEV_A"]]], axis=1)
    elif case == "duplicate_index":
        frame.index = [1] * len(frame)
    elif case == "missing_index":
        frame.index = [None] + list(range(7))
    elif case == "empty":
        frame, domains = frame.iloc[:0], domains.iloc[:0]
    elif case == "domain_order":
        domains = domains.iloc[::-1]
    elif case == "nonboolean":
        domains = domains.astype(int)
    elif case == "missing_domain":
        domains = domains.astype("boolean")
        domains.iloc[0, 0] = pd.NA
    elif case == "duplicate_domain":
        domains = pd.concat([domains, domains[["all"]]], axis=1)
    elif case == "no_domain":
        domains = domains.iloc[:, :0]
    elif case == "not_frame":
        frame = []
    else:
        domains = []
    with pytest.raises(ValueError):
        assess(frame, domains)
